esphome:
  name: ikea_ansluta_example
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Ikea Ansluta Fallback Hotspot"
    password: !secret ap_password

captive_portal:

logger:

api:

ota:

external_components:
  - source: ../components

spi:
  clk_pin: GPIO14
  miso_pin: GPIO12
  mosi_pin: GPIO13

ikea_ansluta:
  cs_pin: GPIO15
  on_remote_click:
    address: 0xdead
    then:
      - light.toggle: my_light

# Using a switch to enable/disable pairing mode
switch:
  - platform: template
    name: "Ikea Ansluta Pairing Mode"
    optimistic: true
    turn_on_action:
      - ikea_ansluta.enable_pairing_mode: my_light
    turn_off_action:
      - ikea_ansluta.disable_pairing_mode: my_light

light:
  - platform: ikea_ansluta
    id: my_light
    name: 'IKEA Ansluta'
    address: 0xbeef
