esphome:
  name: ikea-ansluta-example
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Ikea Ansluta Fallback Hotspot"
    password: !secret ap_password

captive_portal:

logger:

api:

ota:

external_components:
  - source: ../components

spi:
  clk_pin: GPIO14
  miso_pin: GPIO12
  mosi_pin: GPIO13

ikea_ansluta:
  cs_pin: GPIO15
  on_remote_click:
    address: 0xdead
    # If the remote has the same address as the light
    # Then there is no need to turn the light on/off
    # I wouldn't recommend this though, since (at least for me)
    # the performance/stability is actually worse using the remote.
    then:
      - logger.log: "Remote clicked!"

light:
  - platform: ikea_ansluta
    name: 'IKEA Ansluta'
    address: 0xdead # Same adress as remote