esphome:
  name: ikea_ansluta
  platform: ESP8266
  board: d1_mini
  includes:
    - commands.h
    - radio.h
    - ansluta_light.h
    - cc2500_REG.h
    - cc2500_VAL.h
    - cc2500_CMD.h

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Ikea Ansluta Fallback Hotspot"
    password: !secret ap_password

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: false

captive_portal:

logger:

api:

ota:

globals:
  - id: my_global_int
    type: int
    restore_value: no
    initial_value: '0'

custom_component:
  - lambda: |-
      auto ansluta = new Ansluta();
      return {ansluta};
