esphome:
  name: ikea_ansluta
  platform: ESP8266
  board: d1_mini
  includes:
    - ansluta_light.h

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Ikea Ansluta Fallback Hotspot"
    password: !secret ap_password

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password

captive_portal:

logger:

api:

ota:

custom_component:
  - lambda: |-
      auto ansluta = new Ansluta();
      return {ansluta};
