esphome:
  name: ikea_ansluta
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Ikea Ansluta Fallback Hotspot"
    password: !secret ap_password

captive_portal:

logger:

api:

ota:
