name: Test compile with all options

on:
  push:
    branches: [ master, ci-test ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: ESPHome Compile
        run: |
          cd example
          esphome all_options.yaml compile